
#!/usr/bin/env python3
"""
Rivermarsh Game Development Crew - MCP Native Edition
Uses CrewAI's native MCP server integration (no custom adapters needed)
"""

import os
import yaml
from pathlib import Path
from crewai import Agent, Task, Crew, Process
from crewai.utilities import mcp

print("🚀 Initializing Rivermarsh Game Development Crew (MCP Native)")
print("=" * 70)

# ============================================================================
# MCP Server Configuration (Native CrewAI Integration)
# ============================================================================

def setup_mcp_servers():
    """
    Configure MCP servers using CrewAI's native integration.
    Reads from .mcp.json generated by 'ruler apply --nested'.
    
    All agents (Cursor, Claude, Cline, CrewAI) share the same MCP pool
    defined in .ruler/ruler.toml.
    """
    mcp_config_path = Path(".mcp.json")
    
    if not mcp_config_path.exists():
        raise FileNotFoundError(
            f"MCP config not found: {mcp_config_path}\n"
            "Run 'ruler apply --nested' to generate it from .ruler/ruler.toml"
        )
    
    # CrewAI will automatically load and convert all MCP servers to tools
    mcp.load_mcp_servers(str(mcp_config_path))
    print("✓ Loaded MCP servers from .mcp.json (generated by Ruler)")
    
    # Get all available MCP tools
    all_tools = mcp.get_mcp_tools()
    print(f"✓ Available MCP tools: {len(all_tools)}")
    
    return all_tools


# ============================================================================
# LLM Configuration
# ============================================================================

def create_openrouter_llm():
    """
    Configure LLM using OpenRouter.
    Environment variables are set by process-compose.yaml.
    """
    openrouter_key = os.getenv("OPENROUTER_API_KEY")
    
    if openrouter_key:
        print("✓ Using OpenRouter with Claude 3.5 Sonnet")
        print("  Model: openrouter/anthropic/claude-3.5-sonnet")
        
        # Return None - CrewAI will auto-detect from env vars set by process-compose
        return None
    
    # Fallback to direct Anthropic
    anthropic_key = os.getenv("ANTHROPIC_API_KEY")
    if anthropic_key:
        print("⚠️  No OpenRouter key, using direct Anthropic")
        return "anthropic/claude-3-5-sonnet-20241022"
    
    raise ValueError("No API keys found. Set OPENROUTER_API_KEY or ANTHROPIC_API_KEY")


# ============================================================================
# Tool Filtering by Agent Role
# ============================================================================

def filter_tools_for_agent(agent_role: str, all_tools: list) -> list:
    """
    Filter MCP tools based on agent role.
    Each agent gets relevant tools for their domain.
    """
    tool_filters = {
        "Project Manager": [
            "conport_get_product_context",
            "conport_get_active_context", 
            "read_file",
            "list_directory",
            "git_status",
            "git_log",
        ],
        "Technical Writer": [
            "conport_log_decision",
            "conport_update_progress",
            "write_file",
            "read_file",
            "git_status",
        ],
        "Technical Director": all_tools,  # Manager gets all tools
        "ECS Architect": [
            "read_file",
            "write_file",
            "list_directory",
            "fetch_library_docs",  # Context7
        ],
        "Yuka AI Engineer": [
            "read_file",
            "write_file",
            "run_playwright_test",
            "git_diff",
            "fetch_library_docs",
        ],
        "Rendering Engineer": [
            "read_file",
            "write_file",
            "vite_dev_server",
            "run_playwright_test",
            "fetch_library_docs",
        ],
        "Systems Engineer": [
            "read_file",
            "write_file",
            "store_knowledge",
            "retrieve_knowledge",
            "fetch_library_docs",
        ],
        "DFU Analyst": [
            "read_file",
            "write_file",
            "list_directory",
        ],
        "QA Tester": [
            "read_file",
            "run_playwright_test",
            "git_status",
            "git_diff",
        ],
        "Chief Architect": all_tools,
    }
    
    allowed_tool_names = tool_filters.get(agent_role, [])
    
    if allowed_tool_names == all_tools:
        return all_tools
    
    # Filter tools by name
    filtered = []
    for tool in all_tools:
        # MCP tools have a 'name' attribute
        tool_name = getattr(tool, 'name', str(tool))
        if any(allowed in tool_name for allowed in allowed_tool_names):
            filtered.append(tool)
    
    return filtered


# ============================================================================
# Agent & Task Creation from YAML
# ============================================================================

def load_yaml_config(yaml_path: Path) -> dict:
    """Load and parse YAML configuration"""
    with open(yaml_path) as f:
        return yaml.safe_load(f)


def create_agents(agents_config: dict, llm, all_tools: list) -> dict:
    """Create agents from YAML configuration with filtered MCP tools"""
    agents = {}
    
    for agent_name, config in agents_config.items():
        # Filter tools for this agent's role
        agent_tools = filter_tools_for_agent(config['role'], all_tools)
        
        agents[agent_name] = Agent(
            role=config['role'],
            goal=config['goal'],
            backstory=config['backstory'],
            verbose=config.get('verbose', True),
            allow_delegation=config.get('allow_delegation', False),
            llm=llm,
            tools=agent_tools,
        )
        
        print(f"✓ Created agent: {agent_name} ({len(agent_tools)} tools)")
    
    return agents


def create_tasks(tasks_config: dict, agents: dict) -> list:
    """Create tasks from YAML configuration"""
    tasks = []
    
    for task_name, config in tasks_config.items():
        # Get assigned agent
        agent_name = config.get('agent')
        if not agent_name or agent_name not in agents:
            print(f"⚠️  Skipping task {task_name}: agent '{agent_name}' not found")
            continue
        
        task = Task(
            description=config['description'],
            expected_output=config['expected_output'],
            agent=agents[agent_name],
        )
        
        tasks.append(task)
        print(f"✓ Created task: {task_name}")
    
    return tasks


# ============================================================================
# Main Execution
# ============================================================================

def main():
    """Initialize and run the crew"""
    
    # 1. Setup MCP servers (native integration)
    all_tools = setup_mcp_servers()
    
    # 2. Configure LLM
    llm = create_openrouter_llm()
    
    # 3. Load YAML configs
    agents_config = load_yaml_config(Path("crew_config/agents.yaml"))
    tasks_config = load_yaml_config(Path("crew_config/tasks.yaml"))
    
    # 4. Create agents with filtered tools
    agents = create_agents(agents_config, llm, all_tools)
    
    # 5. Create tasks
    tasks = create_tasks(tasks_config, agents)
    
    # 6. Create crew with hierarchical process
    crew = Crew(
        agents=list(agents.values()),
        tasks=tasks,
        process=Process.hierarchical,
        manager_agent=agents.get('technical_director'),
        verbose=True,
    )
    
    print("\n" + "=" * 70)
    print("🎮 Starting Rivermarsh Development Crew")
    print("=" * 70)
    
    # 7. Kickoff crew execution
    result = crew.kickoff()
    
    print("\n" + "=" * 70)
    print("✅ Crew Execution Complete")
    print("=" * 70)
    print(result)
    
    return result


if __name__ == "__main__":
    main()
