
#!/usr/bin/env python3
"""
Rivermarsh Game Development Crew - CrewBase Native Edition
Uses CrewAI's native CrewBase YAML DSL with MCP integration
"""

import os
from pathlib import Path
from crewai import Crew

print("🚀 Initializing Rivermarsh Game Development Crew (CrewBase Native)")
print("=" * 70)

def main():
    """Initialize and run the crew from crewbase.yaml"""
    
    # Verify .mcp.json exists (generated by Ruler)
    mcp_config = Path(".mcp.json")
    if not mcp_config.exists():
        raise FileNotFoundError(
            f"MCP config not found: {mcp_config}\n"
            "Run 'ruler apply --nested' to generate it from .ruler/ruler.toml"
        )
    
    print("✓ Found .mcp.json (generated by Ruler)")
    
    # Verify crewbase.yaml exists
    crewbase_config = Path("python/crew_agents/crewbase.yaml")
    if not crewbase_config.exists():
        raise FileNotFoundError(f"CrewBase config not found: {crewbase_config}")
    
    print("✓ Found crewbase.yaml")
    
    # Verify API keys
    if not os.getenv("OPENROUTER_API_KEY"):
        raise ValueError("OPENROUTER_API_KEY not set")
    
    print("✓ OpenRouter API key configured")
    
    # Create crew from YAML (CrewAI automatically loads MCP tools from .mcp.json)
    crew = Crew.from_yaml(str(crewbase_config))
    
    print("\n" + "=" * 70)
    print("🎮 Starting Rivermarsh Development Crew")
    print(f"Agents: {len(crew.agents)}")
    print(f"Tasks: {len(crew.tasks)}")
    print("=" * 70)
    
    # Kickoff crew execution
    result = crew.kickoff()
    
    print("\n" + "=" * 70)
    print("✅ Crew Execution Complete")
    print("=" * 70)
    print(result)
    
    return result


if __name__ == "__main__":
    main()
