
version: "0.5"

environment:
  - "OPENAI_API_BASE=https://openrouter.ai/api/v1"
  - "OPENAI_MODEL_NAME=openrouter/auto"
  - "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
  - "MESHY_API_KEY=${MESHY_API_KEY}"

log_location: ./logs/crewai
log_level: info

processes:
  # Main Development Crew
  rivermarsh_crew:
    command: "cd python/crew_agents && uv run crewai run"
    working_dir: "."
    depends_on:
      ecs_component_schemas:
        condition: process_completed_successfully
      dfu_data_analysis:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 3
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  terrain_water_rendering:
    command: "cd python/crew_agents && uv run crewai run --task terrain_water_rendering"
    working_dir: "."
    depends_on:
      ecs_component_schemas:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 3
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  quest_dialogue_systems:
    command: "cd python/crew_agents && uv run crewai run --task quest_dialogue_systems"
    working_dir: "."
    depends_on:
      ecs_component_schemas:
        condition: process_completed_successfully
      dfu_data_analysis:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 3
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  performance_testing:
    command: "cd python/crew_agents && uv run crewai run --task performance_testing"
    working_dir: "."
    depends_on:
      yuka_ai_integration:
        condition: process_completed_successfully
      terrain_water_rendering:
        condition: process_completed_successfully
      quest_dialogue_systems:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 2
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  architecture_review:
    command: "cd python/crew_agents && uv run crewai run --task architecture_review"
    working_dir: "."
    depends_on:
      performance_testing:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 2
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  # Continuous monitoring task
  crew_monitor:
    command: "uv run python python/scripts/monitor_crew_progress.py"
    working_dir: "."
    availability:
      restart: "always"
    log_configuration:
      rolling: "daily"
      max_size_mb: 20
      max_backups: 3
    environment:
      - "PYTHONUNBUFFERED=1"
