
version: "0.5"

environment:
  - "OPENAI_API_BASE=https://openrouter.ai/api/v1"
  - "OPENAI_MODEL_NAME=openrouter/auto"
  - "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
  - "MESHY_API_KEY=${MESHY_API_KEY}"
  - "CONPORT_WORKSPACE=${PWD}"

log_location: ./logs
log_level: info

processes:
  # ==============================================================================
  # CONTEXT PORTAL (ConPort) - Project Memory Bank
  # ==============================================================================
  # ConPort provides structured context storage for AI agents.
  # Database is stored in ./context_portal/context.db
  # See: https://github.com/GreatScottyMac/context-portal
  
  conport:
    command: "uvx --from context-portal-mcp conport-mcp --mode stdio --workspace_id ${PWD} --log-file ./logs/conport.log --log-level INFO"
    working_dir: "."
    availability:
      restart: "always"
    log_configuration:
      rolling: "daily"
      max_size_mb: 20
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"
    readiness_probe:
      initial_delay_seconds: 2
      period_seconds: 10
      failure_threshold: 3
      exec:
        command: "test -f ./context_portal/context.db || echo 'db will be created on first use'"

  # Main Development Crew
  rivermarsh_crew:
    command: "cd python/crew_agents && uv run crewai run"
    working_dir: "."
    depends_on:
      ecs_component_schemas:
        condition: process_completed_successfully
      dfu_data_analysis:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 3
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  # Flow-based processes
  tdd_prototype_flow:
    command: "cd python/crew_agents && uv run python -m crew_agents.run_flow tdd_prototype"
    working_dir: "."
    availability:
      restart: "on_failure"
      max_restarts: 2
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  meshy_asset_flow:
    command: "cd python/crew_agents && uv run python -m crew_agents.run_flow meshy_asset otter 'realistic river otter' 'grey fur variant'"
    working_dir: "."
    availability:
      restart: "on_failure"
      max_restarts: 2
    environment:
      - "PYTHONUNBUFFERED=1"

  prototype_assessment_flow:
    command: "cd python/crew_agents && uv run python -m crew_agents.run_flow prototype_assessment biome_selector_diorama"
    working_dir: "."
    depends_on:
      tdd_prototype_flow:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 2
    environment:
      - "PYTHONUNBUFFERED=1"

  terrain_water_rendering:
    command: "cd python/crew_agents && uv run crewai run --task terrain_water_rendering"
    working_dir: "."
    depends_on:
      ecs_component_schemas:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 3
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  quest_dialogue_systems:
    command: "cd python/crew_agents && uv run crewai run --task quest_dialogue_systems"
    working_dir: "."
    depends_on:
      ecs_component_schemas:
        condition: process_completed_successfully
      dfu_data_analysis:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 3
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  performance_testing:
    command: "cd python/crew_agents && uv run crewai run --task performance_testing"
    working_dir: "."
    depends_on:
      yuka_ai_integration:
        condition: process_completed_successfully
      terrain_water_rendering:
        condition: process_completed_successfully
      quest_dialogue_systems:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 2
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  architecture_review:
    command: "cd python/crew_agents && uv run crewai run --task architecture_review"
    working_dir: "."
    depends_on:
      performance_testing:
        condition: process_completed_successfully
    availability:
      restart: "on_failure"
      max_restarts: 2
    log_configuration:
      rolling: "daily"
      max_size_mb: 50
      max_backups: 7
    environment:
      - "PYTHONUNBUFFERED=1"

  # Continuous monitoring task
  crew_monitor:
    command: "uv run python python/scripts/monitor_crew_progress.py"
    working_dir: "."
    availability:
      restart: "always"
    log_configuration:
      rolling: "daily"
      max_size_mb: 20
      max_backups: 3
    environment:
      - "PYTHONUNBUFFERED=1"
